name: Health Check Script

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '*/1 * * * *'  # Runs daily at midnight
      
jobs:
  health-check:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Bash
        run: echo "Bash is already set up in the Ubuntu environment"

      - name: Run Health Check Script
        run: |
          if [ -f ./bash/health_check.sh ]; then
            chmod +x ./bash/health_check.sh
            sudo ./bash/health_check.sh
          else
            echo "Health check script not found!"
            exit 1
          fi
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: health-logs
          path: ./logs
